biom_format:
- 2.1.12
h5py:
- '>=2.10.0,<3.0a0'
hdf5:
- 1.10.6
numpy:
- 1.23.5
pandas:
- '>=1.2.5,<2.0.0'
provenance_lib:
- 2023.5.0.dev0+2.g77aacf2
python:
- '3.8'
q2_alignment:
- 2023.5.0.dev0
q2_assembly:
- 2023.5.0.dev0+3.g8f369c5
q2_checkm:
- 2023.5.0.dev0+3.g2e56081
q2_composition:
- 2023.5.0.dev0+2.g017b756
q2_cutadapt:
- 2023.5.0.dev0
q2_dada2:
- 2023.5.0.dev0
q2_deblur:
- 2023.5.0.dev0
q2_demux:
- 2023.5.0.dev0
q2_diversity:
- 2023.5.0.dev0
q2_diversity_lib:
- 2023.5.0.dev0
q2_emperor:
- 2023.5.0.dev0
q2_feature_classifier:
- 2023.5.0.dev0
q2_feature_table:
- 2023.5.0.dev0+6.g6f2720a
q2_fmt:
- 2023.5.0.dev0+106.gf2266dc
q2_fondue:
- 2023.5.0.dev0+1.g1ed64bf
q2_fragment_insertion:
- 2023.5.0.dev0+1.g48d557a
q2_gneiss:
- 2023.5.0.dev0
q2_longitudinal:
- 2023.5.0.dev0+1.g33db6eb
q2_metadata:
- 2023.5.0.dev0
q2_moshpit:
- 2023.5.0.dev0+5.g2c82db6
q2_mystery_stew:
- 2023.5.0.dev0
q2_phylogeny:
- 2023.5.0.dev0
q2_quality_control:
- 2023.5.0.dev0
q2_quality_filter:
- 2023.5.0.dev0
q2_sample_classifier:
- 2023.5.0.dev0+1.g4c16d88
q2_stats:
- 2023.5.0.dev0+1.g01bbdc9
q2_taxa:
- 2023.5.0.dev0
q2_types:
- 2023.5.0.dev0+2.g8c5db7b
q2_types_genomics:
- 2023.5.0.dev0+4.gc4f304a
q2_vsearch:
- 2023.5.0.dev0
q2cli:
- 2023.5.0.dev0+4.g6019cd7
q2galaxy:
- 2023.5.0.dev0
q2templates:
- 2023.5.0.dev0+2.gc730772
qiime2:
- 2023.5.0.dev0+8.g090f4e0
qiime2_epoch:
- '2023.5'
r_base:
- '>=4.2.0'
rescript:
- 2023.2.0+2.ged0344d
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
